name: Build Blender addon

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies 
        run: |
          pip install pygit2
          ls -la
          pwd
          python --version
          echo "REF=${{ github.event.pull_request && github.head_ref || github.ref_name }}" >> $GITHUB_ENV
      - name: Build addon
        run: |
          python scripts/build_release.py github
          ls -la
      - uses: actions/upload-artifact@v3
        with:
          name: blenderDMX_${{ env.REF }}
          path: build/

